// Import required modules
const express = require('express');
const app = express();

// Define a route for processing incoming requests
app.get('/', (req, res) => {
  // Your processing logic here (generate response)
  const responseData = 'This is the response generated by the JavaScript script.';

  // Return the generated response
  res.send(responseData);
});

// Start the server and listen on localhost at port 3000
const port = 3000;
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
